# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIKitPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIKitPractice

  pod 'TrustKit'

  target 'UIKitPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIKitPracticeUITests' do
    # Pods for testing
  end

end
